variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "true"
    GIT_CLEAN_FLAGS: -f -d -x
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    
cache:
  paths:
    - .cache/pip
    - ./src/ui/angular/mini-sct-gui/node_modules

stages:
    - generate_build_dependencies
    - test
    - integration-test

before_script:
  - $venvPath = ".venv"
  - >
    function Write-PythonPath {
        $pythonPath = $(Get-Command python | % source)
        Write-Output "The python path is at: '$pythonPath'"
    }
  - >
    function Enable-Venv {
        param($VenvPath)

        Invoke-Expression (Join-Path $VenvPath "Scripts/activate.ps1")
        Write-Host "venv enabled at: $VenvPath"
        Write-PythonPath
    }
  - >
    function Create-Venv {
        param($VenvPath)

        Write-Output "Creating venv at $VenvPath ."
        py -m venv $VenvPath
        Write-Output "venv created at $VenvPath ."
    }
  - >
    function Install-PythonRequirements {
        param($VenvPath)

        py -m pip install -U pip setuptools wheel
        pip install -e .
        pip install -r requirements.txt
    }
  - >       
    function Install-AngularRequirementsAndBuild {
        param($VenvPath)

        cd .\src\ATE\ui\angular\mini-sct-gui
        npm i @angular/core
        npm i tslint-eslint-rules
        ng build
    }
  - >
    function Remove-Venv {
        param($VenvPath)

        Remove-Item $VenvPath -Recurse -Force
        Write-Host "venv removed from: $VenvPath"
    }

  - Get-Location

build_venv:
  stage: generate_build_dependencies
  artifacts:
    expire_in: '10 mins'
    paths:
      - .venv
  script:
    - Create-Venv $venvPath
    - Enable-Venv $VenvPath
    - Install-PythonRequirements $venvPath
  tags:
    - pyt

build_angular_dependencies:
  stage: generate_build_dependencies
  script:
    - Install-AngularRequirementsAndBuild $venvPath
    - ng lint
    - ng test --watch false --browsers ChromeHeadless
  tags:
    - pyt
    
#angular_test:
#  stage: test
#  script:
#   - cd .\src\ATE\ui\angular\mini-sct-gui
#   - ng test --watch false --browsers ChromeHeadless
#  tags:
#   - pyt
    
pytest:
  stage: test
  script:
   - Enable-Venv $venvPath
   - pytest --cov=. tests\apps
  dependencies:
   - build_venv
  tags:
   - pyt

pytest-stdf:
  stage: test
  script:
   - Enable-Venv $venvPath
   - pytest --cov=. tests\stdf
  dependencies:
   - build_venv
  tags:
   - pyt

pytest-qt:
  stage: test
  script:
   - Enable-Venv $venvPath
   - pytest --cov=. tests\qt
  dependencies:
   - build_venv
  tags:
   - pyt
   
pytest-integration:
  stage: integration-test
  script:
    - Enable-Venv $venvPath
    # HACK: manually create directory for http server:
    # the files are currently not used, but the directory
    # must exist or master will not start.
    # TODO: eventually we need to fix this CI script to
    # preserve the anular build output between jobs
    - mkdir .\src\ATE\ui\angular\mini-sct-gui\dist\mini-sct-gui
    - $env:ATE_INTEGRATION_TESTENV_BROKER_HOST='10.9.1.6'
    - $env:ATE_INTEGRATION_TESTENV_DEVICE_ID = "gitlab_CI_"+$CI_PIPELINE_ID
    - $env:PIPELINE_ID = $CI_PIPELINE_ID
    # TODO: use --cov-append to combine coverage stats from test and integration-test? or simply don't split these into two jobs anymore?
    - python -m pytest -v -o log_cli=true --cov=. tests\integration_tests
  dependencies:
   - build_venv
  tags:
   - pyt

