language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to run tests
script:
  - pytest tests/qt