language: python
dist: xenial
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
services:
  - xvfb
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

# command to run tests
script:
  - pytest tests/qt