language: python
dist: xenial
services:
  - xvfb
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

# command to run tests
script:
  - pytest tests/qt